# Generated by Django 5.0.4 on 2024-04-19 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cif', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.IntegerField(max_length=15)),
                ('email', models.EmailField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('cod_ref_comp', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'componente',
                'verbose_name_plural': 'componentes',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('cod_ref_ped', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appDeustronicComponents.cliente')),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('cod_ref_prod', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('categoria', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('componente', models.ManyToManyField(to='appDeustronicComponents.componente')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='PedidoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appDeustronicComponents.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appDeustronicComponents.producto')),
            ],
            options={
                'verbose_name': 'detalle pedido',
                'verbose_name_plural': 'detalle pedidos',
                'ordering': ['-created'],
            },
        ),
    ]
