# Generated by Django 5.0.4 on 2024-04-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appDeustronicComponents', '0003_remove_pedido_precio_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidoproducto',
            name='precio_total',
        ),
        migrations.AddField(
            model_name='pedido',
            name='precio_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
