# Generated by Django 5.0.4 on 2024-05-18 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appDeustronicComponents', '0006_alter_cliente_password_alter_cliente_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='password',
            field=models.CharField(max_length=16),
        ),
    ]
