# Generated by Django 5.0.4 on 2024-05-25 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appDeustronicComponents', '0008_pedido_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='password',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='username',
        ),
    ]
